#160: Use BCP-47 with implicit conversion
GlobalDigitalLibraryio/image-api pull request #32
Opened 2018-01-22 08:39 UTC by runarfu

GlobalDigitalLibraryio/issues#160

2018-01-24 09:33 UTC, kstigen requested changes
Er det en grunn til at vi ikke benytter `LanguageTag` også i modellene om omhandler søk? For så å serialisere dem til/fra elasticsearch? 

Også i input til søkegrensesnittet? Kanskje ikke nødvendig å gi en feil dersom man søker etter bilder på et språk som ikke er gyldig. Holder vel å gi en tom liste.

Er vi sikre på at dataene som vi allerede har har god nok kvalitet til at dette ikke kommer til å eksplodere når det deployes? Har vi språkkode på alle bilder, eller importerer vi dem som `unknown`?

2018-01-24 09:33 UTC, kstigen commented on src/main/scala/no/ndla/imageapi/controller/ImageController.scala
> +    protected implicit override val jsonFormats: Formats = DefaultFormats + new LanguageTagSerializer
Tror denne er redundant. Vi setter allerede `jsonFormats` i `NdlaController`, som denne klassen arver

2018-01-24 09:33 UTC, kstigen commented on src/main/scala/no/ndla/imageapi/controller/ImageControllerV2.scala
> +    protected implicit override val jsonFormats: Formats = DefaultFormats + new LanguageTagSerializer
Redundant

2018-01-24 14:14 UTC, runarfu commented on src/main/scala/no/ndla/imageapi/controller/ImageController.scala
> +    protected implicit override val jsonFormats: Formats = DefaultFormats + new LanguageTagSerializer
Tenkte at denne var overridet av en grunn, derfor satte jeg `LanguageTagSerializer` også her. Men nå er de jo identiske, så du har rett i at den er redundant. Fjernet.

2018-01-24 14:17 UTC, runarfu commented
> Er det en grunn til at vi ikke benytter LanguageTag også i modellene om omhandler søk? For så å serialisere dem til/fra elasticsearch?

Nei, det har jeg bare glemt. Fikser!

> Også i input til søkegrensesnittet? Kanskje ikke nødvendig å gi en feil dersom man søker etter bilder på et språk som ikke er gyldig. Holder vel å gi en tom liste.

Enig.

> Er vi sikre på at dataene som vi allerede har har god nok kvalitet til at dette ikke kommer til å eksplodere når det deployes? Har vi språkkode på alle bilder, eller importerer vi dem som unknown?

Ja, fordi språket på alle bilder som blir importert via bokimport kommer fra språket på boka, og det har hele tiden blitt validert.

2018-01-25 08:30 UTC, runarfu commented
@kstigen Sett over kommentarer på QA og utbedret. Tar du en ny titt ved anledning?

2018-01-26 09:38 UTC, kstigen approved these changes

2018-01-26 11:07 UTC, merged